site_name: GeMSE Toolkit Docs
repo_url: https://github.com/mucahit-kaya/GeMSE_toolkit
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
nav:
  - Home: index.md            # docs/index.md
  - User Guide:
      - Run environment: run-environment.md
      - Analyze spectrum: analyze-spectrum.md
  - Development:
      - Dev notes: dev/index.md
